### ISSUE TITLE
RF calculations wrong for multiple non-continuous pulse emission

### ISSUE THREAD

**Issue by cardosan** [gschivley/ghgforcing#2]
HI Greg,
it seems that the RF calculations is wrong. Give a look at the attached notebook, the results should be different no?
[CO2_WRONG.ipynb.zip](https://github.com/gschivley/ghgforcing/files/627286/CO2_WRONG.ipynb.zip)

**Comment by cardosan** [comment]
I made a mistake, did not see the timestep.
everythings works as expected, sorry :S

**Comment by gschivley** [comment]
Thanks for taking a look at the package. I think the calculations are right - see my edits in [this notebook](https://gist.github.com/gschivley/7cf567e19d758a38a701fcd448a47425). Emissions in year 50 should be located at idx 5000 of the numpy array when using a timestep of 0.01 (`co2_emission[5000]`). And because it was set up for continuous emission functions, the mass of pulse emissions need to be divided by the timestep. The model does need to take inputs in a better format, which would make this more clear.

**Comment by gschivley** [comment]
No problem, I'm glad that someone else is taking a look at it! Let me know if you have any suggestions for how to improve the design or code. Hopefully in the next month or two I'll be doing a complete clean-up of the code (putting functions in classes, improving efficiency, etc).

**Comment by cardosan** [comment]
Hi Greg,
I had the intention to use in ghgforcing in  [termporalis](https://bitbucket.org/cardosan/brightway2-temporalis/overview) to have a complete dynamic LCA package.
The idea is to use it to calculate GWP (thus would need also to include some others gasses) also considering the timing of emissions (i.e. Levasseur approach) and the GWPbio (Cherubini), really relevant to me that am working with forests and wood sector....this is the idea, need to check how much work this would involve :)

I would be more than happy to collaborate on this development and maybe write something together later (my actual final goal of this work).

**Comment by gschivley** [comment]
Sure. I'm wrapping up a paper and a project at the moment, but should have some time once those are done. Go ahead and create issues for any specific improvements you want to suggest.
